export const DELETE_AVAILABLE_BIKE = 'DELETE_AVAILABLE_BIKE'
export const SET_AVAILABLE_BIKES = 'SET_AVAILABLE_BIKES'
export const SET_RENTED_BIKES = 'SET_RENTED_BIKES'
export const MOVE_RENT_BIKE = 'MOVE_RENT_BIKE'
export const MOVE_AVAILABLE_BIKE = 'MOVE_AVAILABLE_BIKE'
export const CANCEL_RENT_BIKE = 'CANCEL_RENT_BIKE'

